### ISSUE TITLE
[BUG] AttributeError: type object 'Retry' has no attribute 'DEFAULT_BACKOFF_MAX'

### ISSUE THREAD

**Issue by callanova** [salt-extensions/saltext-vault#93]
**Description**
When running sudo salt-run commands (e.g., `sudo salt-run vault`) I receive the following error:
```
[ERROR   ] Failed to import runners vault, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/salt/runner.py", line 230, in run
    verify_fun(self.functions, low["fun"])
  File "/usr/local/lib/python3.10/dist-packages/salt/utils/lazy.py", line 24, in verify_fun
    raise salt.exceptions.CommandExecutionError(lazy_obj.missing_fun_string(fun))
salt.exceptions.CommandExecutionError: 'vault' is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/salt/loader/lazy.py", line 785, in _load_module
    mod = self.run(spec.loader.load_module)
  File "/usr/local/lib/python3.10/dist-packages/salt/loader/lazy.py", line 1245, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/salt/loader/lazy.py", line 1260, in _run_as
    return _func_or_method(*args, **kwargs)
  File "<frozen importlib._bootstrap_external>", line 548, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1063, in load_module
  File "<frozen importlib._bootstrap_external>", line 888, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/saltext/vault/runners/vault.py", line 26, in <module>
    from saltext.vault.utils import vault
  File "/usr/local/lib/python3.10/dist-packages/saltext/vault/utils/vault/__init__.py", line 23, in <module>
    from saltext.vault.utils.vault.factory import clear_cache
  File "/usr/local/lib/python3.10/dist-packages/saltext/vault/utils/vault/factory.py", line 23, in <module>
    from saltext.vault.utils.vault import client as vclient
  File "/usr/local/lib/python3.10/dist-packages/saltext/vault/utils/vault/client.py", line 643, in <module>
    class VaultRetry(Retry):
  File "/usr/local/lib/python3.10/dist-packages/saltext/vault/utils/vault/client.py", line 662, in VaultRetry
    backoff_max=Retry.DEFAULT_BACKOFF_MAX,
AttributeError: type object 'Retry' has no attribute 'DEFAULT_BACKOFF_MAX'
```
If I manually edit `/usr/local/lib/python3.10/dist-packages/saltext/vault/utils/vault/client.py` and replace this line:
`backoff_max=Retry.DEFAULT_BACKOFF_MAX,`
with this:
`backoff_max=DEFAULT_BACKOFF_MAX,`
everything works as expected.

Based on that, it looks like `Retry.` might need to be removed from this line:
https://github.com/salt-extensions/saltext-vault/blob/main/src/saltext/vault/utils/vault/client.py#L662

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [X] on-prem machine

**Steps to Reproduce the behavior**
Install salt-master and saltext-vault.
Attempt to run any `salt-run vault` command.

**Expected behavior**
Ability to run salt-run commands such as `salt-run vault.sync_approles '*'` and `salt-run vault.sync_entities '*'`.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3006.6

Python Version:
        Python: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]

Dependency Versions:
          cffi: 1.17.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.8
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 24.1
     pycparser: 2.22
      pycrypto: Not Installed
  pycryptodome: 3.20.0
        pygit2: Not Installed
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 25.0.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

Salt Extensions:
 saltext.vault: 1.2.0

System Versions:
          dist: ubuntu 22.04.5 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-124-generic
        system: Linux
       version: Ubuntu 22.04.5 jammy
```
</details>

**Additional context**

**Comment by lkubb** [comment]
Can you post the output of `salt-pip list` on your master, specifically the `requests` and `urllib3` versions? The 3006.6 onedir [pins urllib3](https://github.com/saltstack/salt/blob/v3006.6/requirements/static/pkg/py3.10/linux.txt#L99) to `1.26.18`, which provides Retry.DEFAULT_BACKOFF_MAX (introduced in `1.26.6`).

`urllib3.utils.retry.Retry.DEFAULT_BACKOFF_MAX` is different from `saltext.vault.utils.vault.client.DEFAULT_BACKOFF_MAX`, but this shouldn't matter in practice.

**Comment by callanova** [comment]
Yep, looks like it was urllib3 version that was the problem.
Sorry about that!
Thanks for the help!
